services:
  - type: web
    name: simuphysics
    env: node
    plan: free
    healthCheckPath: /health
    buildCommand: npm install
    startCommand: node app.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUBLIC_BASE_URL
        value: https://simuphysics.onrender.com
      - key: SIMS_DIRECTORY_PATH
        value: ./simulations
